# fly.toml file generated for grepo on 2022-07-07T12:53:13-03:00

app = "grepo"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  dockerfile = "FlyDockerfile"
  [build.args]
    BUNDLER_VERSION = "2.3.7"
    NODE_VERSION = "14"
    RUBY_VERSION = ">= 3.1.1"

[env]
  SERVER_COMMAND = "bundle exec sidekiq -e production -C config/sidekiq.yml"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
