# fly.toml file generated for grepo on 2022-07-07T12:53:13-03:00

app = "sidekiq-greyrepo"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  dockerfile = "FlyDockerfile"
  [build.args]
    BUNDLER_VERSION = "2.4.4"
    NODE_VERSION = "18"
    RUBY_VERSION = ">= 3.2.0"

[env]
  SERVER_COMMAND = "bundle exec sidekiq -e production -C config/sidekiq.yml & bundle exec clockwork lib/clock.rb"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
